from pydantic import BaseModel, Field
from typing import Optional, List
from datetime import datetime

"""
Database Models

These represent the data we actually store in Supabase.
They're similar to database table schemas.

Why separate from VapiWebhookPayload?
- VAPI sends us everything, but we only store what matters
- Database models include IDs, timestamps we create, indexes
- Makes queries predictable and type-safe
"""

# ============================================================================
# CALL RECORD MODEL
# ============================================================================

class CallRecord(BaseModel):
    """
    A single call record stored in our database.
    
    This is what gets stored in the 'calls' table in Supabase.
    
    Think of it like a spreadsheet row:
    | id | call_id | phone_number | started_at | ended_at | duration_seconds | status | transcript | created_at |
    """

    # ---- IDs ----
    id: Optional[int] = Field(
        None,
        description="Database primary key (auto-generated by Supabase)"
    )
    """
    Why id?
    - Every record needs a unique identifier
    - Supabase auto-generates this (serial primary key)
    - We use it to query, update, delete specific calls
    - We don't set this; the database does
    """

    call_id: str = Field(
        ...,
        description="VAPI's unique call ID"
    )
    """
    Why call_id separate from id?
    - id is OUR database key (for this service)
    - call_id is VAPI's key (for their system)
    - If we ever integrate with other platforms, call_id helps us match records
    """

    # ---- Caller Info ----
    phone_number: Optional[str] = Field(
        None,
        description="The caller's phone number"
    )

    caller_name: Optional[str] = Field(
        None,
        description="Extracted caller name from the conversation (if Nova captured it)"
    )
    """
    Why we have this separate field:
    - Phone number alone isn't enough
    - Nova should extract the caller's name from the conversation
    - We'll add logic to capture this from the transcript
    - Example: Caller says "Hi, my name is Sarah", we extract "Sarah"
    """

    reason_for_call: Optional[str] = Field(
        None,
        description="The reason they called (extracted from conversation)"
    )
    """
    Why reason_for_call:
    - Nova should understand why they called
    - Helps triage calls (urgent vs routine)
    - Example: "Schedule appointment" or "Check order status"
    """

    # ---- Call Timing ----
    started_at: datetime = Field(
        ...,
        description="When the call started"
    )
    """
    Why datetime fields matter:
    - Know when calls happen (peak hours?)
    - Sort/filter calls chronologically
    - Audit trail (compliance)
    """

    ended_at: Optional[datetime] = Field(
        None,
        description="When the call ended"
    )

    duration_seconds: Optional[int] = Field(
        None,
        description="How long the call lasted"
    )
    """
    Why track duration:
    - Short calls might be wrong number/hang-ups
    - Long calls might indicate complexity
    - KPI for customer service (avg call time)
    """

    # ---- Call Content ----
    transcript: Optional[str] = Field(
        None,
        description="Full transcript of the call (messages concatenated)"
    )
    """
    Why store the full transcript:
    - Complete record for auditing/compliance
    - Can search for specific keywords later
    - Proof of what was discussed
    - We'll concatenate all messages into one text field for simplicity
    
    Format (we'll build this from the messages list):
    "User: Hi, I'd like to schedule an appointment
    Assistant: Sure! What time works for you?
    User: How about Tuesday at 2pm?
    ..."
    """

    summary: Optional[str] = Field(
        None,
        description="VAPI's AI summary of the call"
    )
    """
    Why summary:
    - Quick overview without reading full transcript
    - VAPI generates this automatically
    - Example: "Caller requested appointment scheduling"
    """

    sentiment: Optional[str] = Field(
        None,
        description="Sentiment analysis: positive, negative, or neutral"
    )
    """
    Why sentiment:
    - Indicates caller satisfaction
    - Negative sentiment might mean we need follow-up
    - Positive = good experience
    """

    # ---- Status ----
    status: str = Field(
        ...,
        description="Call outcome: 'completed', 'failed', 'no_answer', etc."
    )
    """
    Why status:
    - 'completed' = successful call
    - 'failed' = technical error
    - 'no_answer' = caller hung up early
    - Helps us track call quality
    """

    error_message: Optional[str] = Field(
        None,
        description="If status is 'failed', what went wrong"
    )

    # ---- Metadata ----
    assistant_id: Optional[str] = Field(
        None,
        description="Which assistant handled this (should be 'nova')"
    )

    created_at: Optional[datetime] = Field(
        None,
        description="When we stored this record in our database (not when the call happened)"
    )
    """
    Why created_at:
    - started_at = when the call happened
    - created_at = when we stored it in the database
    - Usually the same, but useful for debugging delays
    - Supabase sets this automatically with: DEFAULT CURRENT_TIMESTAMP
    """

    class Config:
        """
        Tells Pydantic how to handle this model.
        """
        json_schema_extra = {
            "example": {
                "id": 1,
                "call_id": "call_abc123",
                "phone_number": "+1-234-567-8900",
                "caller_name": "John Smith",
                "reason_for_call": "Schedule appointment",
                "started_at": "2024-01-15T10:30:45Z",
                "ended_at": "2024-01-15T10:35:12Z",
                "duration_seconds": 287,
                "transcript": "Assistant: Hi! How can I help?...",
                "summary": "Caller requested appointment",
                "sentiment": "positive",
                "status": "completed",
                "assistant_id": "nova",
                "created_at": "2024-01-15T10:35:15Z"
            }
        }


# ============================================================================
# REQUEST/RESPONSE MODELS (For our API endpoints)
# ============================================================================

class CallRecordCreate(BaseModel):
    """
    What we need to CREATE a new call record.
    Subset of CallRecord (doesn't include id, created_at).
    """
    call_id: str
    phone_number: Optional[str] = None
    caller_name: Optional[str] = None
    reason_for_call: Optional[str] = None
    started_at: datetime
    ended_at: Optional[datetime] = None
    duration_seconds: Optional[int] = None
    transcript: Optional[str] = None
    summary: Optional[str] = None
    sentiment: Optional[str] = None
    status: str
    error_message: Optional[str] = None
    assistant_id: Optional[str] = None

    """
    Why a separate Create model?
    - Clients don't send 'id' or 'created_at' (database generates these)
    - Keeps request validation separate from storage
    - API docs are clearer (shows what clients actually need to send)
    """


class CallRecordUpdate(BaseModel):
    """
    What we can UPDATE on an existing call record.
    All fields optional (we might only update the status, for example).
    """
    caller_name: Optional[str] = None
    reason_for_call: Optional[str] = None
    ended_at: Optional[datetime] = None
    duration_seconds: Optional[int] = None
    transcript: Optional[str] = None
    summary: Optional[str] = None
    sentiment: Optional[str] = None
    status: Optional[str] = None
    error_message: Optional[str] = None

    """
    Why optional?
    - Partial updates (don't need to send every field)
    - Example: only update status when call ends
    """


class CallRecordResponse(BaseModel):
    """
    What we return when queried.
    Includes everything (since it already exists in DB).
    """
    id: int
    call_id: str
    phone_number: Optional[str] = None
    caller_name: Optional[str] = None
    reason_for_call: Optional[str] = None
    started_at: datetime
    ended_at: Optional[datetime] = None
    duration_seconds: Optional[int] = None
    transcript: Optional[str] = None
    summary: Optional[str] = None
    sentiment: Optional[str] = None
    status: str
    error_message: Optional[str] = None
    assistant_id: Optional[str] = None
    created_at: datetime

    """
    Why separate Response model?
    - Response includes 'id' and 'created_at' (database-generated)
    - Request (Create) doesn't include these
    - Clean separation of concerns
    - API docs show users what to expect back
    """

    class Config:
        from_attributes = True
        """
        from_attributes=True allows Pydantic to read from database objects
        Example: if database returns a SQLAlchemy object, Pydantic can convert it
        """