from pydantic import BaseModel, Field
from typing import Optional, List
from datetime import datetime

"""
VAPI Webhook Schemas

What is a schema?
- A schema defines the structure of data we expect to receive
- Pydantic validates incoming data against the schema
- If data doesn't match (wrong types, missing fields), Pydantic rejects it

Why separate schemas into their own file?
- Keeps them organized and reusable
- Other files can import these and use them for validation
- Easy to update all at once if VAPI changes their format
"""

# ============================================================================
# MESSAGE MODELS (For conversation transcripts)
# ============================================================================

class Message(BaseModel):
    """
    A single message in the call transcript.
    
    Example:
    {
        "role": "user",  # The caller
        "message": "Hi, I'd like to schedule an appointment",
        "timestamp": 1705323456
    }
    """
    role: Optional[str] = Field(None, description="'user' (caller) or 'assistant' (Nova)")
    message: Optional[str] = Field(None, description="The actual text of what was said")
    timestamp: Optional[int] = Field(None, description="Unix timestamp of when this was said")

    class Config:
        populate_by_name = True
        extra = "allow"


# ============================================================================
# ANALYSIS MODEL (Results after call ends)
# ============================================================================

class AnalysisResult(BaseModel):
    """
    Analysis of the call performed by VAPI after the call ends.
    
    VAPI can analyze:
    - Summary: What was the call about?
    - Sentiment: Was the caller happy, angry, neutral?
    - Action items: What needs to happen next?
    - Structured data: Extracted info like name, phone, etc.
    
    We won't use all of these for now, but having the schema makes
    it easy to capture them later.
    """
    summary: Optional[str] = Field(None, description="Brief summary of the call")
    sentiment: Optional[str] = Field(None, description="Overall sentiment: positive, negative, neutral")
    action_items: Optional[List[str]] = Field(None, description="List of action items discussed")
    custom_analysis: Optional[dict] = Field(None, description="Any custom analysis VAPI performed")

    class Config:
        populate_by_name = True
        extra = "allow"


# ============================================================================
# MAIN WEBHOOK PAYLOAD (What VAPI sends us)
# ============================================================================

class VapiWebhookPayload(BaseModel):
    """
    The complete webhook payload VAPI sends when a call ends.
    
    Made flexible to handle VAPI's actual payload format.
    All fields are optional to match what VAPI actually sends.
    """

    # ---- Call Metadata ----
    call_id: Optional[str] = Field(
        None, 
        description="Unique ID for this call, generated by VAPI"
    )

    phone_number: Optional[str] = Field(
        None, 
        description="The phone number of the caller"
    )

    assistant_id: Optional[str] = Field(
        None,
        description="ID of the assistant (Nova in our case)"
    )

    # ---- Timing ----
    started_at: Optional[datetime] = Field(
        None,
        description="When the call started (ISO 8601 timestamp)"
    )
    
    ended_at: Optional[datetime] = Field(
        None,
        description="When the call ended (ISO 8601 timestamp)"
    )

    duration_seconds: Optional[int] = Field(
        None,
        description="Total call duration in seconds"
    )
    

    # ---- Conversation ----
    messages: Optional[List[Message]] = Field(
        None,
        description="List of all messages in the call transcript"
    )
   

    # ---- Analysis ----
    analysis: Optional[AnalysisResult] = Field(
        None,
        description="VAPI's post-call analysis results"
    )

    # ---- Status ----
    status: Optional[str] = Field(
        None,
        description="Call status: 'completed', 'failed', 'ended', etc."
    )
    

    error_message: Optional[str] = Field(
        None,
        description="If status is failed, this explains why"
    )

    # ---- VAPI Metadata ----
    model: Optional[str] = Field(
        None,
        description="The LLM model used (should be llama-3.1-8b)"
    )

    webhook_event_type: Optional[str] = Field(
        None,
        description="Type of webhook event: 'message', 'call-ended', etc."
    )

    class Config:
        """
        Pydantic config for this model.
        populate_by_name allows flexibility in field names.
        extra = "allow" accepts any fields VAPI sends that we don't explicitly define.
        """
        populate_by_name = True
        extra = "allow"
        json_schema_extra = {
            "example": {
                "call_id": "call_abc123xyz",
                "phone_number": "+1-234-567-8900",
                "assistant_id": "nova-v1",
                "started_at": "2024-01-15T10:30:45Z",
                "ended_at": "2024-01-15T10:35:12Z",
                "duration_seconds": 287,
                "messages": [
                    {
                        "role": "assistant",
                        "message": "Hi! Thanks for calling. How can I help you today?",
                        "timestamp": 1705323045
                    },
                    {
                        "role": "user",
                        "message": "I'd like to schedule an appointment",
                        "timestamp": 1705323051
                    }
                ],
                "analysis": {
                    "summary": "Caller wants to schedule an appointment",
                    "sentiment": "positive",
                    "action_items": ["Schedule appointment for caller"]
                },
                "status": "completed",
                "model": "llama-3.1-8b",
                "webhook_event_type": "call-ended"
            }
        }


# ============================================================================
# WEBHOOK RESPONSE MODEL (What we send back to VAPI)
# ============================================================================

class VapiWebhookResponse(BaseModel):
    """
    The response we send back to VAPI after receiving a webhook.
    
    VAPI expects a specific format back, otherwise it thinks
    the webhook failed and may retry.
    """
    success: bool = Field(..., description="Whether we successfully processed the webhook")
    message: str = Field(..., description="A message describing what happened")

    class Config:
        json_schema_extra = {
            "example": {
                "success": True,
                "message": "Call data stored successfully"
            }
        }